version: '2.2'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: node01
    environment:
      - node.name=node01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://node01:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "q87pAK/9tFaipeTgdXJPhd9zN2PbgDW/Sma/d0AcWI8="
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - node01

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.11.1
    container_name: metricbeat
    environment:
      - ELASTICSEARCH_HOSTS=http://node01:9200
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - metricbeat-data01:/usr/share/metricbeat/data
    networks:
      - es-network
    depends_on:
      - node01
      - kibana
    command: >
      sh -c "metricbeat setup --dashboards && metricbeat -e"

  logstash:
    build:
      context: logstash/
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5050:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es-network
    depends_on:
      - node01      

volumes:
  es-data01:
    driver: local
  metricbeat-data01:
    driver: local

networks:
  es-network:
    driver: bridge